### ISSUE TITLE
Create alternate password reset page

### ISSUE THREAD

**Issue by owoc** [Animagia/cardstack#7]
Implement as a page template.

If currently logged in user is not an administrator, print a blank page.

Otherwise, show an input field that will accept a username or email of another user and generate and print a password reset link for that user. The link must be exactly the same as what WordPress' built-in password reset would generate and send via email.

This is meant as backup measure for when someone's inbox refuses to receive password reset emails.

**Comment by Kajeczko** [comment]
Info: By default 'reset password key' expire after one day.
